package packagekey

import "strings"

// ParseComposerPath extracts a Composer package coordinate from one of the
// cache-key route shapes generated by the Composer adapter. Only the complete
// per-package p2 metadata route and the reversible dist mirror key establish
// an identity; packages.json, indexes, and arbitrary passthrough paths return
// false.
//
// The input is relative to the Composer adapter (for example,
// "p2/symfony/console.json"), with an optional leading slash accepted for
// callers that pass an HTTP path.
func ParseComposerPath(path string) (string, bool) {
	path = strings.TrimPrefix(path, "/")
	switch {
	case strings.HasPrefix(path, "p2/"):
		return parseComposerP2Path(strings.TrimPrefix(path, "p2/"))
	case strings.HasPrefix(path, "dist/"):
		return parseComposerDistPath(strings.TrimPrefix(path, "dist/"))
	default:
		return "", false
	}
}

// ParseComposerRequestPath extracts the identity carried by a Composer HTTP
// route. The dist mirror URL has one more route component than its cache key:
// `dist/<vendor>/<package>/<version_normalized>/<reference>.<type>`. The
// normalized version is returned for callers that need an audit target, but
// it is not treated as an operator-visible pretty version by Composer's
// Package Rule capability.
func ParseComposerRequestPath(path string) (name, version string, ok bool) {
	path = strings.TrimPrefix(path, "/")
	if strings.HasPrefix(path, "p2/") {
		name, ok := ParseComposerPath(path)
		return name, "", ok
	}
	if !strings.HasPrefix(path, "dist/") {
		return "", "", false
	}
	parts := strings.Split(strings.TrimPrefix(path, "dist/"), "/")
	if len(parts) < 4 {
		return "", "", false
	}
	name, ok = composerCoordinate(parts[0] + "/" + parts[1])
	if !ok {
		return "", "", false
	}
	version = strings.Join(parts[2:len(parts)-1], "/")
	if !validComposerRouteValue(version, true) {
		return "", "", false
	}
	last := parts[len(parts)-1]
	dot := strings.IndexByte(last, '.')
	if dot <= 0 || dot == len(last)-1 ||
		!validComposerArtifactToken(last[:dot]) ||
		!validComposerRouteValue(last[dot+1:], false) {
		return "", "", false
	}
	return name, version, true
}

func parseComposerP2Path(path string) (string, bool) {
	// A p2 URL is exactly p2/<vendor>/<package>.json, with ~dev inserted
	// immediately before the extension for branch metadata. Requiring exactly
	// one coordinate slash prevents a look-alike such as p2/not-a-package from
	// becoming an OSV identity.
	if !strings.HasSuffix(path, ".json") {
		return "", false
	}
	coordinate := strings.TrimSuffix(path, ".json")
	if strings.HasSuffix(coordinate, "~dev") {
		coordinate = strings.TrimSuffix(coordinate, "~dev")
	}
	return composerCoordinate(coordinate)
}

func parseComposerDistPath(path string) (string, bool) {
	// DistCacheKey intentionally omits version_normalized because the
	// reference is the immutable artifact identity. Its generated shape is
	// exactly dist/<vendor>/<package>/<reference>.<type>. A strict three-part
	// split keeps arbitrary metadata paths from being interpreted as packages.
	parts := strings.Split(path, "/")
	if len(parts) != 3 {
		return "", false
	}
	artifact := parts[2]
	dot := strings.LastIndexByte(artifact, '.')
	if dot <= 0 || dot == len(artifact)-1 || !validComposerArtifactToken(artifact) {
		return "", false
	}
	return composerCoordinate(parts[0] + "/" + parts[1])
}

func composerCoordinate(value string) (string, bool) {
	parts := strings.Split(value, "/")
	if len(parts) != 2 || !validComposerNamePart(parts[0], 1) ||
		!validComposerNamePart(parts[1], 2) ||
		strings.HasSuffix(strings.ToLower(parts[1]), ".json") {
		return "", false
	}
	return parts[0] + "/" + parts[1], true
}

func validComposerNamePart(value string, maxHyphenRun int) bool {
	if value == "" || value == "." || value == ".." ||
		!isASCIIComposerAlphanumeric(value[0]) ||
		!isASCIIComposerAlphanumeric(value[len(value)-1]) {
		return false
	}
	for index := 0; index < len(value); {
		if isASCIIComposerAlphanumeric(value[index]) {
			index++
			continue
		}
		separator := value[index]
		if separator != '.' && separator != '_' && separator != '-' {
			return false
		}
		runStart := index
		for index < len(value) && value[index] == separator {
			index++
		}
		maxRun := 1
		if separator == '-' {
			maxRun = maxHyphenRun
		}
		if index-runStart > maxRun || index == len(value) ||
			!isASCIIComposerAlphanumeric(value[index]) {
			return false
		}
	}
	return true
}

func validComposerArtifactToken(value string) bool {
	if value == "" {
		return false
	}
	for index := range len(value) {
		character := value[index]
		if isASCIIComposerAlphanumeric(character) || strings.ContainsRune("._-", rune(character)) {
			continue
		}
		return false
	}
	return true
}

func validComposerRouteValue(value string, allowSlash bool) bool {
	if value == "" {
		return false
	}
	parts := []string{value}
	if allowSlash {
		parts = strings.Split(value, "/")
	}
	for _, part := range parts {
		if part == "" || part == "." || part == ".." || !validComposerArtifactToken(part) {
			return false
		}
	}
	return true
}

func isASCIIComposerAlphanumeric(character byte) bool {
	return character >= 'A' && character <= 'Z' ||
		character >= 'a' && character <= 'z' ||
		character >= '0' && character <= '9'
}
