# typed: false
# frozen_string_literal: true

# This formula is auto-generated by GoReleaser.
# Manual edits will be overwritten on the next release.
#
# To install:
#   brew tap depsilo/tap
#   brew install depsilo

class Depsilo < Formula
  desc "Lightweight self-hosted dependency cache for 14 package managers"
  homepage "https://depsilo.com"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/depsilo/depsilo/releases/download/v0.5.0/depsilo_0.5.0_darwin_amd64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"
    end
    if Hardware::CPU.arm?
      url "https://github.com/depsilo/depsilo/releases/download/v0.5.0/depsilo_0.5.0_darwin_arm64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/depsilo/depsilo/releases/download/v0.5.0/depsilo_0.5.0_linux_amd64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"
    end
    if Hardware::CPU.arm?
      url "https://github.com/depsilo/depsilo/releases/download/v0.5.0/depsilo_0.5.0_linux_arm64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"
    end
  end

  def install
    bin.install "depsilo"
  end

  test do
    system "#{bin}/depsilo", "version"
  end
end
