// Package compilecache implements the shared compiler artifact cache used by
// protocol-specific data-plane adapters. It is intentionally independent from
// the package-proxy cache.
package compilecache

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strings"
)

var (
	ErrInvalidKey       = errors.New("invalid compiler-cache key")
	ErrInvalidNamespace = errors.New("invalid compile-cache namespace")
	ErrInvalidProtocol  = errors.New("invalid compile-cache protocol")
)

// Protocol identifies the client protocol that produced an opaque artifact.
// It is part of the logical and physical cache identity so implementations
// with different key or value formats can never hit each other's entries.
type Protocol string

const (
	ProtocolCCache  Protocol = "ccache"
	ProtocolSCCache Protocol = "sccache"
)

// ArtifactID is the validated identity accepted by Service. Its fields are
// deliberately private: protocol adapters must use the constructors below,
// which keep URL parsing and key-format rules outside the storage Module.
type ArtifactID struct {
	protocol  Protocol
	namespace string
	key       string
}

// Protocol returns the artifact's protocol identity.
func (id ArtifactID) Protocol() Protocol { return id.protocol }

// Namespace returns the artifact's validated cache namespace.
func (id ArtifactID) Namespace() string { return id.namespace }

// Key returns the artifact's canonical protocol key.
func (id ArtifactID) Key() string { return id.key }

func (id ArtifactID) validate() error {
	validated, err := NewArtifactID(id.protocol, id.namespace, id.key)
	if err != nil {
		return err
	}
	if validated != id {
		return ErrInvalidKey
	}
	return nil
}

var namespacePattern = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9._-]{0,62}[a-z0-9])?$`)

// NormalizeNamespace accepts a stable URL/storage-safe namespace. Namespaces
// are intentionally lowercase and bounded so they can be used with both local
// paths and object-store keys without backend-specific escaping.
func NormalizeNamespace(raw string) (string, error) {
	namespace := strings.TrimSpace(raw)
	if !namespacePattern.MatchString(namespace) {
		return "", fmt.Errorf("%w: use 1-64 lowercase letters, digits, '.', '_' or '-'", ErrInvalidNamespace)
	}
	return namespace, nil
}

// ParseHTTPKey accepts ccache's default subdirs and flat layouts. Ccache 4.13+
// uses a 40-character hexadecimal digest; ccache 4.4-4.12 uses 4 hexadecimal
// characters followed by 29 base32hex characters.
func ParseHTTPKey(raw string) (string, error) {
	path := strings.TrimPrefix(raw, "/")
	key := path
	if len(path) > 2 && path[2] == '/' {
		key = path[:2] + path[3:]
	}
	switch len(key) {
	case 40:
		for _, char := range key {
			if char < '0' || char > '9' {
				if char < 'a' || char > 'f' {
					return "", fmt.Errorf("%w: modern keys must be lowercase hexadecimal", ErrInvalidKey)
				}
			}
		}
	case 33:
		for index, char := range key {
			if char < '0' || char > '9' {
				maxLetter := 'v'
				if index < 4 {
					maxLetter = 'f'
				}
				if char < 'a' || char > maxLetter {
					return "", fmt.Errorf("%w: legacy keys must use lowercase base32hex characters", ErrInvalidKey)
				}
			}
		}
	default:
		return "", fmt.Errorf("%w: expected a 33-character legacy or 40-character modern key", ErrInvalidKey)
	}
	return key, nil
}

// ParseSCCacheKey accepts the object layout generated by sccache's WebDAV
// backend: the first three digest nibbles as directories followed by the full
// 64-character lowercase hexadecimal BLAKE3 key.
func ParseSCCacheKey(raw string) (string, error) {
	path := strings.TrimPrefix(raw, "/")
	parts := strings.Split(path, "/")
	if len(parts) != 4 || len(parts[0]) != 1 || len(parts[1]) != 1 || len(parts[2]) != 1 || len(parts[3]) != 64 {
		return "", fmt.Errorf("%w: expected a/b/c/<64 lowercase hexadecimal characters>", ErrInvalidKey)
	}
	key := parts[3]
	for _, char := range key {
		if (char < '0' || char > '9') && (char < 'a' || char > 'f') {
			return "", fmt.Errorf("%w: sccache keys must be lowercase hexadecimal", ErrInvalidKey)
		}
	}
	if parts[0]+parts[1]+parts[2] != key[:3] {
		return "", fmt.Errorf("%w: sccache directory prefix does not match the key", ErrInvalidKey)
	}
	return key, nil
}

// NewArtifactID accepts a canonical key without URL layout components.
func NewArtifactID(protocol Protocol, namespace, key string) (ArtifactID, error) {
	normalizedNamespace, err := NormalizeNamespace(namespace)
	if err != nil {
		return ArtifactID{}, err
	}
	switch protocol {
	case ProtocolCCache:
		parsed, parseErr := ParseHTTPKey(key)
		if parseErr != nil || parsed != key {
			if parseErr != nil {
				return ArtifactID{}, parseErr
			}
			return ArtifactID{}, ErrInvalidKey
		}
	case ProtocolSCCache:
		if len(key) != 64 {
			return ArtifactID{}, fmt.Errorf("%w: expected a 64-character sccache key", ErrInvalidKey)
		}
		for _, char := range key {
			if (char < '0' || char > '9') && (char < 'a' || char > 'f') {
				return ArtifactID{}, fmt.Errorf("%w: sccache keys must be lowercase hexadecimal", ErrInvalidKey)
			}
		}
	default:
		return ArtifactID{}, fmt.Errorf("%w: %q", ErrInvalidProtocol, protocol)
	}
	return ArtifactID{protocol: protocol, namespace: normalizedNamespace, key: key}, nil
}

// ParseCCacheArtifact validates a namespace and ccache HTTP key layout.
func ParseCCacheArtifact(namespace, rawKey string) (ArtifactID, error) {
	key, err := ParseHTTPKey(rawKey)
	if err != nil {
		return ArtifactID{}, err
	}
	return NewArtifactID(ProtocolCCache, namespace, key)
}

// ParseSCCacheArtifact validates a namespace and sccache WebDAV object path.
func ParseSCCacheArtifact(namespace, rawPath string) (ArtifactID, error) {
	key, err := ParseSCCacheKey(rawPath)
	if err != nil {
		return ArtifactID{}, err
	}
	return NewArtifactID(ProtocolSCCache, namespace, key)
}

func newObjectPath(id ArtifactID) (string, error) {
	if err := id.validate(); err != nil {
		return "", err
	}
	generation := make([]byte, 16)
	if _, err := rand.Read(generation); err != nil {
		return "", fmt.Errorf("generate compiler-cache object path: %w", err)
	}
	return "v1/" + string(id.protocol) + "/" + id.namespace + "/objects/" + id.key[:2] + "/" + id.key[2:] + "/" + hex.EncodeToString(generation), nil
}

func newProbeObjectPath() (string, error) {
	generation := make([]byte, 16)
	if _, err := rand.Read(generation); err != nil {
		return "", fmt.Errorf("generate compiler-cache probe path: %w", err)
	}
	return "v1/probes/" + hex.EncodeToString(generation), nil
}

func objectPathMatchesArtifact(id ArtifactID, storagePath string) bool {
	currentPrefix := "v1/" + string(id.protocol) + "/" + id.namespace + "/objects/" + id.key[:2] + "/" + id.key[2:] + "/"
	if strings.HasPrefix(storagePath, currentPrefix) {
		return true
	}
	// v0.8's ccache-only preview did not include a protocol segment. Preserve
	// those objects in place when their metadata is backfilled during upgrade.
	legacyPrefix := "v1/" + id.namespace + "/objects/" + id.key[:2] + "/" + id.key[2:] + "/"
	return id.protocol == ProtocolCCache && strings.HasPrefix(storagePath, legacyPrefix)
}
